Jcn 354 subtarea agregar type def en api list
janis-commerce/api-list pull request #10
Opened 2022-02-10 15:44 UTC by guillecipri

**Link a las tareas:**
[Tarea](https://fizzmod.atlassian.net/browse/JCN-329)
[Subtarea](https://fizzmod.atlassian.net/browse/JCN-354)

**Requerimiento:**
Agregar TypeDef al package de Api-List

2022-02-16 19:48 UTC, argenis1763 commented on lib/api-list-data.js
> + * @typedef {Object} ApiListError A instance of ApiListError class
No necesitas declarar **ApiListError** puedes hacer referencia directamente a ella porque esta siendo requerida, lo importante es que este bien documentada la clase.

2022-02-16 20:15 UTC, argenis1763 requested changes

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-data.js
> +	 * @throws {ApiListError}
Al menos una descripción genérica no vendría mal y colocaria el `throws` antes del `returns`

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-data.js
> +	 * @return {Promise<void>}
El `validate` no retorna

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-data.js
>  class ApiListData extends API {
Estaria bueno colocar una breve descripción de la clase. Puedes fijarte como se hace en el packages de `Microservice-Call`

```
/**
 * @class MicroServiceCall
 * @classdesc Use this to make request to a Janis Microservice.
 */
```

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-data.js
> +	 * @throws {ApiGetError} if the model not exists
Me parece que esto deberia ser **ApiListError**

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-data.js
> +	 * Set the modelName, recordId and parents of API after parsing the endpoint
El `recordId` no se setea en el **API List**

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-error.js
> + * @typedef {Object} Error An instance of Error class
No es necesario declarar este tipo porque es propio de JS, lo puedes utilizar haciendo referencia a `Error`

2022-02-16 20:15 UTC, argenis1763 commented on lib/api-list-error.js
>  class ApiListError extends Error {
Al igual que el **API List** sumemos una breve descripción de la clase.

2022-02-17 11:16 UTC, guillecipri commented
Agregué algunas cositas mas que no me marcaste, pero como tambien tengo en correccion api-save, aproveché y metí cambios que me había pedido Gaston ahí (a los get e indicar si son async los metodos)

2022-02-17 18:14 UTC, argenis1763 commented on lib/api-list-error.js
> + * @classdesc An instance of Error class.
Me parece que una descripción mas clara sería ```It is used for error handling of the APIListData class```

2022-02-17 18:32 UTC, argenis1763 approved these changes
:+1:

2022-02-22 14:22 UTC, gastonpereyra commented on lib/api-list-data.js
>  module.exports = ApiListData;
Aprovechemos para cambiar esto y exportar directamente

2022-02-22 14:29 UTC, gastonpereyra commented on lib/api-list-data.js
>  class ApiListData extends API {
Se podría agregar las definciones para `formatFilters` y `formatRows` que son importanes y estan para agregarlos al extender

2022-02-22 14:30 UTC, gastonpereyra commented on lib/api-list-error.js
>  class ApiListError extends Error {
También podemos aprovechar para exportar la clase directamente

2022-02-22 14:30 UTC, gastonpereyra requested changes
Algunas mejoras

2022-02-23 13:41 UTC, gastonpereyra commented on lib/api-list-data.js
> +			const rows = this.formatRows(result);
:warning: 

Aca estas cambiando seriamente el funcionamiento, este método era async y lo mejor es que lo siga siendo

2022-02-23 13:43 UTC, gastonpereyra commented on lib/api-list-data.js
> +		return filters;
Aca retornaria nada `return;` . Porque sino entraria todo el tiempo en el `if` y solo tiene que entrar cuando se elija hacer una modificación especial para esto

2022-02-23 13:45 UTC, gastonpereyra requested changes
Algunos comentarios sobre un cambio no deseado

2022-02-23 16:59 UTC, gastonpereyra approved these changes
:+1:

2022-03-02 13:18 UTC, merged