Jcn 366 subtarea1 sumar parametros custom a api list
janis-commerce/api-list pull request #12
Opened 2022-03-16 19:18 UTC by guillecipri

**Requerimiento**
Se requiere modificar el package para que sea posible sumar parámetros custom a las API LIST creadas con el :package:.

Nuevo getter
Se debe sumar un nuevo **getter** opcional `customParameters` que permita configurar un struct para sumar al actual (el que ya valida filters, sortBy y sortDirection)

Se debe documentar el nuevo **getter** y sumar un ejemplo claro.

Solución:
- Se agregó el nuevo **getter** y sus test.
- Se documentó en `README`

2022-03-17 16:03 UTC, Nataniel4 requested changes
Detalles a revisar

2022-03-17 16:03 UTC, Nataniel4 commented on CHANGELOG.md
> +- New optional field `customParameters`.
Mmm no exactamente 👀 lo que agregaste fue un getter `customParameters`, como referencia un ejemplo para el changelog seria algo como:

"Optional getter `customParameters` in `apiListData` class for API custom query parameters"

2022-03-17 16:03 UTC, Nataniel4 commented on README.md
> +This is used to set custom parameters for the request. It's optional. Additional parameters will be arrives by `this.data`.
"This allows you to set custom **query parameters** for your API, it must contain the names of the custom parameters that the API will receive"

y para el ejemplo, quizas algo que ayude a que se entienda mejor el proposito de esto
```js
'use strict';

const { ApiListData } = require('@janiscommerce/api-list');

module.exports = class MyApi extends ApiListData {

    get customParameters() {
        return ['additionalParameter']
    }
}

/* 
    This will allow the API to use custom query parameters, example:
    https://domain.com/api/my-api-list?additionalParameter='someData'
*/
```

2022-03-17 16:03 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +			[customParameter]: struct.optional('string')
Mmm esto creo que no va a funcionar, en los customParameters te va a llegar un array de strings, cada uno con el nombre de los custom parameters que se necesiten. Pero aca solo estas devolviendo uno solo. Lo que tenes que hacer es recorrer los items en custom parameters y meterlos en el object de salida:

```js
struct() {

    if(!this.customParameters.length)
        return {};

    return this.customParameters.reduce((customParameters, parameterName) => {
        customParameters[parameterName] = struct.optional('string');
        return customParameters;
    },{})
}
```

2022-03-18 19:22 UTC, Nataniel4 requested changes
Solo unos detallitos y estamos :)

2022-03-18 19:22 UTC, Nataniel4 commented on lib/api-list-data.js
> +	 * Get the customParameters.
"Get the custom query parameters" 😌

2022-03-18 19:22 UTC, Nataniel4 commented on lib/api-list-data.js
> +	 * @returns {Object} - The custom parameters.
En lugar de "The custom parameters" usemos "The custom query parameters struct" 🤓

2022-03-18 19:22 UTC, Nataniel4 commented on lib/api-list-data.js
> +		this.customParameter.validate();
Me di cuenta de que si este validate rompe, porque algo esta mal, va a arrojar un error comun cuando lo que queremos es que sea un error con el codigo de error correcto, como se ve en el try catch que viene despues. Propongo acomodar las cosas de esta forma (rezando que no rompa los tests mucho):

```js
try {

	this.customParameter.validate();
	this.sort.validate();

	const listDataStruct = struct({
		...this.customParameter.struct(),
		...this.filter.struct(),
		...this.sort.struct(),
	}, {
		...this.filter.defaults(),
		...this.sort.defaults()
	});

	this.dataWithDefaults = listDataStruct({
		...this.data,
		...(Object.keys(requestFilters).length ? { filters: requestFilters } : {})
	});

} catch (e) {
	throw new ApiListError(e, ApiListError.codes.INVALID_REQUEST_DATA);
}
```

2022-03-18 19:22 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +			throw new Error('The custom parameter must be an object');
Aca te quedo en singular 😭 "The custom parameter***s*** must be an object"

2022-03-18 19:22 UTC, Nataniel4 commented on tests/api-list-data.js
> +				apiListData.data =
Te quedo un salto de linea medio turbina 😱

2022-03-18 19:22 UTC, Nataniel4 commented on tests/api-list-data.js
> +				await assert.rejects(() => apiListData.validate(), err => {
Si recuerdo bien el `assert.rejects`, a diferencia del `assert.throws`, no necesita que le pases una función y el segundo parametro me parece que ya devuelve objeto de error 🤔 

Así deberia funcar:
```js
assert.rejects(apiListData.validate(), {
    message: 'The custom parameters must be an object"
});
```
O tal vez me volvi loco 😛

2022-03-18 19:22 UTC, Nataniel4 commented on README.md
> +```
Acá nos falto como es que se accede a los parámetros desde la API, nos faltaría documentar que los parámetros llegan dentro del `this.data` y agregar un ejemplo de uso también 🥺

2022-03-23 13:13 UTC, Nataniel4 requested changes

2022-03-23 13:13 UTC, Nataniel4 commented on README.md
> +- `valueMapper`: (function) A function to be called on the filter's value. This is optional.
"filter's value" 🙀 en este caso seria el "parameter's value" 😌

2022-03-23 13:13 UTC, Nataniel4 commented on README.md
> +				valueMapper: booleanMapper
Mmm para el ejemplo usaria un ejemplo mas generico ya que booleanMapper no sabemos de donde viene en el contexto del ejemplo. Capaz algo asi:
```js
{
    name: 'numericParam',
    valueMapper: Number
}
```

2022-03-23 13:13 UTC, Nataniel4 commented on README.md
> +Can be customized by passing an object with the following properties:
Falta aclarar que recibe o un string o un object, porque aca dice que es solo un object 😭

2022-03-23 13:13 UTC, Nataniel4 commented on lib/api-list-data.js
> +			this.customParameter.formatCustomParameters(this.data);
Como viene de la clase "customParameter" el metodo podria llamarse solo "format" porque ya esta implicito que serian los customParameters 🤓

2022-03-23 13:13 UTC, Nataniel4 commented on lib/helpers/mapper-filter.js
> +module.exports.mapperFilter = (originalValue, valueMapper) => {
El helper puede exportar la funcion directamente ya que es lo unico que exporta 😌

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +		this.validate({ customParameters });
El validate vamos a llamarlo en el metodo format, no puede estar en el constructor porque si rompe no va a entrar en el try catch de api-list-data 🙀

2022-03-23 13:13 UTC, Nataniel4 commented on lib/api-list-data.js
> +			this.customParameter.formatCustomParameters(this.data);
Aca no hace falta que le pases el this.data porque tu clase CustomParameter ya la tiene 👀

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +
Este salto de linea lo podemos fletar 💅

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +		const customParameters = [...this.customParameters];
Porque estas clonando el array? el reduce devuelve un array nuevo 🤔 se puede usar directamente `this.customParameters`

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +		this.customParameters = customParameters.map(customParameter => {
En el constructor dejemos que this.customParameters sea tal cual como llega en `customParameters`, esta parte vamos a moverla al metodo format 😉

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +		return this.customParameters.filter(params => {
Bien, en este metodo no recibimos parametros, podemos tomar los customParameters directamente desde el `this.customParameters`, este metodo primero tiene que llamar al `validate` y luego hacer exactamente lo que actualmente esta haciendo el constructor al final que es tirar el map sobre el this.customParameters y hacer que todos los items sean objetos

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +	validate(customParameters) {
Este metodo tampoco va a necesitar parametros porque puede tomarlo del `this.customParameters` 😌

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +const apiCustomParameterStruct = {
⚠️ Ojo, este struct tiene que validar mejor porque en el caso de los customParameters, estos llegan en el `this.data` junto con los de filtrado y ordenamiento de la API, por lo que tenemos que hacer que el struct valide que de todos los customParameters que puedan llegar **no sean nombres reservados para otros parametros de la API**

Por ejemplo, si alguien quiere meter un custom parameter que es `sortBy` estaria pisando el `sortBy` de la API y seguramente rompan las validaciones de los otros data-helpers.

Los parametros reservados de la API list que puedan llegar en el `this.data` son `filters`, `sortBy` y `sortDirection` 👀

2022-03-23 13:13 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +			struct(apiCustomParameterStruct)(customParameters);
Dejemos solo el struct aca y no usemos el try catch, porque esto se va a llamar dentro del metodo format, que se llama desde api-list-data dentro de su propio try catch :)

2022-03-23 18:51 UTC, guillecipri commented on lib/data-helpers/custom-parameter.js
> +		this.customParameters = customParameters.map(customParameter => {
este cambio no lo hice porque me rompía todo

2022-03-25 12:38 UTC, Nataniel4 requested changes

2022-03-25 12:38 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +			struct(apiCustomParameterStruct)({ customParameters: this.customParameters });
Tenemos que hacer que el struct del validate se use antes de hacer el map de los customParameters, hagamos asi, dejemos el constructor asi:
```js
constructor(requestParameters, customParameters) {
	this.requestParameters = requestParameters;
	this.customParameters = customParameters;
}
```

Y vamos a sacar el metodo `validate` como tal y dejar la validacion en el mismo format porque nos esta complicando la vida el struct, despues el map y aaaaaaaa 💥

**Como? Asi:**
Despues de hacer los cambios en el constructor como puse arriba, vamos a combinar el `format` con el `validate` dejando el `format` algo asi:
```js

try {

	struct(apiCustomParameterStruct)({ customParameters: this.customParameters });

	this.customParameters = this.customParameters.reduce(( formattedParameters, parameter ) => {

		parameter = typeof parameter === 'object' ? parameter : { name: parameter };

		if(apiReservedParams.includes(parameter.name))
			throw new Error(`The custom parameter name "${parameter.name}" is a reserved parameter name.`);

		if(this.requestParameters[parameter.name] === undefined)
			return formattedParameters;

		this.requestParameters[parameter.name] = mapperFilter(this.requestParameters[parameter.name], parameter.valueMapper);

		formattedParameters.push(parameter);
		return formattedParameters;

	}, []);

} catch(error) {
	throw new ApiListError(error, ApiListError.codes.INVALID_PARAMETERS);
}
```

No deberia (👁️ _ 👁️) romper los tests y simplificaria las cosas 😌

2022-03-25 12:38 UTC, Nataniel4 commented on lib/data-helpers/custom-parameter.js
> +
Movamos la variable de las "reservedWords" afuera de la clase, aca antes del module.exports (y de paso le ponemos un mejor nombre):
```js

const apiReservedParams = [
	'filters',
	'sortBy',
	'sortDirection'
];

module.exports = class ListCustomParameters {
	// ...
```

2022-03-25 18:45 UTC, Nataniel4 approved these changes

2022-03-28 15:48 UTC, merged