add formatSortables method
janis-commerce/api-list pull request #16
Opened 2022-07-15 18:16 UTC by Alejandro-Gonzalez

**Link Ticket**

[JCN-402](https://fizzmod.atlassian.net/browse/JCN-402)
[JCN-401(History)](https://fizzmod.atlassian.net/browse/JCN-401)

**Descripción**
Se deberá implementar la función de “ordenamientos customs” al igual que se hacen con los filtros
El getter sortableFields deberá poder recibir un array de las siguientes cosas:
- Strings (tal cual como funciona actualmente)
- Objetos
- - En donde cada objeto deberá recibir:
- - - **name**: nombre del ordenamiento
- - - **valueMapper**: función custom a aplicar

Se deberá disponibilizar un método `formatSortables`
Deberá recibir los ordenamientos y devolver los mismos
Dicho método se deberá llamarse solo en caso de que exista en la api (tal cual lo hace `formatFilters`)

**Solución**
Se agrego el nuevo método `formatSortables`, tests y documentación.

2022-07-18 12:57 UTC, Nataniel4 requested changes
Lo que esta, esta bien pero a lo mejor no estoy viendo bien pero no encuentro que se cumpla este requerimiento, ni en código, ni en documentación ni tests:

```
El getter sortableFields deberá poder recibir un array de las siguientes cosas:
- Strings (tal cual como funciona actualmente)
- Objetos
En donde cada objeto deberá recibir: <--- 👀
 - name: nombre del ordenamiento
 - valueMapper: función custom a aplicar
```

Esperaba algo parecido a como sucede con los filtros que usan un objeto `{ name, valueMapper }` que agrega una posibilidad de no tener que usar `formatSortables` en casos simples 😌

2022-07-20 13:22 UTC, Nataniel4 requested changes

2022-07-20 13:22 UTC, Nataniel4 commented on lib/data-helpers/sort.js
> +			let direction = DEFAULT_SORT_DIRECTION;
Sugerencia 🤓 
```
const direction = (this.isString(sortDirection) && sortDirection) ||
    (Array.isArray(sortDirection) && sortDirection[index]) ||
    DEFAULT_SORT_DIRECTION;
```

2022-07-20 13:22 UTC, Nataniel4 commented on lib/data-helpers/sort.js
> +	isArray(value) {
Por que no usar `Array.isArray()` directamente? 🤔

2022-07-22 13:48 UTC, Nataniel4 approved these changes

2022-07-26 21:59 UTC, gastonpereyra commented on README.md
> +			name: 'foo',
Estaria bueno explicar que significa cada cosa del Array, y cual es el default. Asi queda a interpretación del usuario.

Y otra cosa estaria bueno que diga para que utilizar esto.

Porque pensé que el default de la dirección era `desc` y era `asc`

2022-07-26 22:07 UTC, gastonpereyra commented on lib/data-helpers/sort.js
>  		if(!sortParameters || !sortParameters.length)
Te parece ?
```suggestion
		if(!sortParameters?.length)
```

2022-07-26 22:21 UTC, gastonpereyra reviewed
Deje una sugerencia.

El valueMapper como función con esta implementación da igual que sea una función, porque el unico valor que recibe por parametro es el nombre del filtro, entonces no tiene mucho dinamismo asi.

Entonces:

> Opción 1
`valueMapper` podria no ser función solo el valor.

> Opción 2

Que siga como función pero que reciba la dirección y adentro poder hacer algo con eso, por ejemplo:

Si tengo que ordena por 2 campos (status y fecha),

* dirección `asc`: status -> asc, fecha -> desc
* dirección `desc`: status -> desc, fecha -> asc

Como esta ahora no se podria tener sorts con ordenamientos cruzados,  salvo metele logica en el formatSortables, cuando es algo que se podria hacer aca más fácil.

Y además permitiria hacer otras cosas, solo para un filtro.

Qué les parece?

2022-07-28 23:29 UTC, gastonpereyra approved these changes

2022-08-04 18:56 UTC, merged