JCN-417-add-fields-getter
janis-commerce/api-list pull request #17
Opened 2022-11-30 18:13 UTC by luisfer00

**Links:**
[Historia](https://fizzmod.atlassian.net/browse/JCN-410) - [Subtarea](https://fizzmod.atlassian.net/browse/JCN-417)

**DESCRIPCIÓN DEL REQUERIMIENTO:**
Se requiere modificar el package [GitHub - janis-commerce/api-list: A package to handle JANIS List APIs](https://github.com/janis-commerce/api-list) para sumar un nuevo parámetro opcional fields.

El parámetro fields, si se recibe, debe ser una Array de strings

Al ser recibido, justo antes de devolver el listado de objetos, se debe reducir la respuesta según los fields recibidos

Si se recibe un field que no se encuentra en la respuesta, se debe ignorar sin fallar la ejecución

Siempre se debe devolver el campo `id`

**DESCRIPCIÓN DE LA SOLUCIÓN:**

- Se añadió el getter `fields()` para que la api devuelva solos los campos que se declaren en el getter, ademas del campo `id
`.
- Se añadieron tests para probar dicha funcionalidad.
- Se añadieron los cambios al CHANGELOG.md.
- Se añadió la descripción del nuevo comportamiento al README.md.

2022-12-02 19:08 UTC, calandrajose commented on README.md
> +This is used to select the fields that will be returned.
esto estaria bueno que este en lineas diferentes. Cuando se arma el readme esta quedando todo en una oracion

2022-12-02 20:39 UTC, calandrajose commented on README.md
> +### get fields()
esto estaria bueno que este en lineas diferentes. Cuando se arma el readme esta quedando todo en una oracion

2022-12-02 20:39 UTC, calandrajose commented on lib/api-list-data.js
> +				if(row[field] !== undefined)
esto funciona? no necesitas un typeof?

2022-12-02 20:39 UTC, calandrajose commented on tests/api-list-data.js
> +				class MyModel {
esto podrias definirlo afuera, no tiene mucho sentido que cada test cree esta clase

2022-12-02 20:39 UTC, calandrajose commented on tests/api-list-data.js
> +				assert.deepStrictEqual(apiListData.response.body, [deletefields(row, ['b', 'c'])]);
siento que era mas facil traer el que querias que borrar todos los demas jajaja

2022-12-07 17:57 UTC, luisfer00 commented on lib/api-list-data.js
> +				if(row[field] !== undefined)
Si funciona, pero tambien funciona con el typeof, para mantener una base de código similar lo voy a cambiar a un typeof 👍

2022-12-12 14:25 UTC, calandrajose approved these changes
:+1:

2022-12-12 20:18 UTC, mdanelutti requested changes
Un cambio menor

2022-12-12 20:18 UTC, mdanelutti commented on lib/api-list-data.js
> +				rows = this._selectFields(rows);
no me convence que pasemos `rows` a `let` solo para volverlo a pisar por `fields`, dejaría `const` y al final `this.setBody(this._selectFields(rows));` a fin de cuentas el primer IF que haces adentro de `this._selectFields` resuelve la validación que haces acá en la linea 192

2022-12-21 17:11 UTC, mdanelutti approved these changes

2022-12-23 20:20 UTC, juanhapes requested changes

2022-12-23 20:20 UTC, juanhapes commented on tests/api-list-data.js
> +			class MyModel {
No entiendo por qué tenemos el `get()` y `getTotals()` así definidos en vez de hacer `sinon.stub().resolves()` directamente como siempre...

2022-12-23 20:20 UTC, juanhapes commented on tests/api-list-data.js
> +				sinon.assert.calledOnceWithExactly(MyModel.prototype.get, { page: 1, limit: 60 });
Esta linea y la próxima la sumaste 5 veces (en todos tus tests que sumaste)
Recomiendo meter un `afterEach(() => {})` y ponerlo 1 sola vez ahí lo que se repita

2022-12-27 12:48 UTC, merged