Jcn 440 modify apilist package to use totals
janis-commerce/api-list pull request #18
Opened 2023-08-10 21:13 UTC by parodimatias

2023-08-14 21:54 UTC, Alejandro-Gonzalez requested changes

2023-08-14 21:54 UTC, Alejandro-Gonzalez commented on tests/api-list-data.js
> +				sinon.restore();
@parodimatias acá en ves de el sinon.restore y los stubs, podes meter solo
`MyModel.prototype.get.resolves([]);`

2023-08-14 21:54 UTC, Alejandro-Gonzalez commented on tests/api-list-data.js
> +
@parodimatias guarda con estos dobles espacios, dejar solo uno.

2023-08-14 21:54 UTC, Alejandro-Gonzalez commented on tests/api-list-data.js
> +
@parodimatias acá dejar 1 espacio nomas

2023-08-14 21:54 UTC, Alejandro-Gonzalez commented on lib/api-list-data.js
>  			const { result, total } = await this.fetchData(getParams);
@parodimatias aca antes del `fetchData`, podriamos meter 
```js
this.calculateCalculateOnlyTotals = this.shouldCalculateOnlyTotals();
this.calculateTotals = this.shouldCalculateTotals();
```

Así las usas tanto en el método fetchData, como en este mas abajo, asi reutilizamos.

2023-08-14 21:54 UTC, Alejandro-Gonzalez commented on tests/api-list-data.js
> +			it('Should calculate totals when x-janis-only-totals header received as true', async () => {
@parodimatias aca podemos reutlizar un toque y hacer lo suguiente

```js
[true, 'true', '1'].forEach(value => {
	it(`Should calculate totals when x-janis-only-totals header received as ${value}${typeof value}`, async () => {

		const myApiList = getApiInstance(ApiListData, {
			headers: { 'x-janis-only-totals': value }
		});

		await myApiList.validate();

		await myApiList.process();

		sinon.assert.calledOnce(MyModel.prototype.getTotals);
		sinon.assert.notCalled(MyModel.prototype.get);

		assert.deepStrictEqual(myApiList.response.headers, { 'x-janis-total': 1 });
		assert.deepStrictEqual(myApiList.response.body, undefined);
	});
});

[false, 'false', '0'].forEach(value => {
	it(`Should not calculate totals when x-janis-only-totals header received as ${value}(${typeof value})`, async () => {

		const myApiList = getApiInstance(ApiListData, {
			headers: { 'x-janis-only-totals': value }
		});

		await myApiList.validate();

		await myApiList.process();

		sinon.assert.notCalled(MyModel.prototype.getTotals);
		sinon.assert.calledOnce(MyModel.prototype.get);

		assert.deepStrictEqual(myApiList.response.headers, {});
	});
});
```

2023-08-16 16:00 UTC, Alejandro-Gonzalez approved these changes

2023-08-17 19:22 UTC, gastonpereyra commented on lib/api-list-data.js
> +			const { total } = await this.model.getTotals();
:warning: :warning: :warning:

Esto funciona solo en un caso particular y no funciona en el resto.

### Caso que si Funciona
Consulta a la API List sin ningún filtro.

### Casos en los que no
Consultas con filtros, que es talvés lo mas habitual.

2023-08-17 19:45 UTC, gastonpereyra requested changes

2023-08-17 19:45 UTC, gastonpereyra commented on lib/api-list-data.js
> +			const { total } = await this.model.getTotals();
Esto quiere decir que al pedir los totales con filtros este dando falsos resultados y se va a paginar mal.

### Por qué pasa ?
Si te fijas en como funciona el `getTotals` veras que se usan los parametros que se cargan en los `get` o trae todo si no hubo `get` previo.

### Cómo solucionarlo ?
Una posible solución es detectar si hay o no que devolver los resultados,

En caso de tener que devolverlos simplemente se ejecuta el `get` antes y listo.

En caso de no tener que devolverlos, hay que chequear si filtros activados.
* Si NO hay filtros, se puede usar el `getTotals` asi nomás.
* Si HAY filtros, se tendria que hacer un `get` con `limit: 1` (para que no busque mucho), y asi settear los filtros correctamente antes de hacer un `getTotals`

Ya luego seguir.

2023-08-17 19:45 UTC, gastonpereyra commented on lib/api-list-data.js
>  	shouldCalculateTotals() {
Aca yo revisaria los 2 Headers que pueden devolver los totales.

2023-08-17 19:45 UTC, gastonpereyra commented on lib/api-list-data.js
> +	shouldCalculateOnlyTotals() {
Aca cambiaria el enfoque, para mi el método deberia ser si debe retornar el `get`. (al reves de este)

2023-08-17 19:45 UTC, gastonpereyra commented on lib/api-list-data.js
>  	async fetchData(getParams) {
Aca lo que haria es:

- Preguntar si debe retornar el body (el `get`)
- ---- En caso afirmativo hacer el `get` y quedarse con `results`.
- ---- En caso negativo no haces nada y `results` que sea `undefined`
- Preguntar si debe buscar los totales
- ---- En caso negativo no se busca nada y se sigue, `total` no tiene nada
- ---- En caso afirmativo buscar los totales (siguiendo el comentario que deje sobre `getTotals` con o sin filtros)
- Devolver `results` y `totals` 

### Por qué ?
Ahora en 2 partes diferentes se calculan los totales, cuando se puede hacer solo 1 vez.

2023-09-05 19:07 UTC, gastonpereyra commented on lib/api-list-data.js
> +			this.shouldReturnOnlyTotal = this.shouldCalculateOnlyTotals();
Como puse en otros comentarios anteriores, solo tendria 1 variable `shouldReturnTotals` 
```suggestion
			this.shouldReturnTotal = this.shouldCalculateTotals() || this.shouldCalculateOnlyTotals();
```

2023-09-05 19:07 UTC, gastonpereyra commented on lib/api-list-data.js
> +			this.shouldReturnBody = !this.shouldReturnOnlyTotal;
```suggestion
			this.shouldReturnBody = !this.shouldCalculateOnlyTotals();
```

2023-09-05 19:08 UTC, gastonpereyra commented on lib/api-list-data.js
> +			if(this.shouldReturnTotal || this.shouldReturnOnlyTotal)
```suggestion
			if(this.shouldReturnTotal)
```

2023-09-05 19:08 UTC, gastonpereyra commented on lib/api-list-data.js
> +		if(this.shouldReturnOnlyTotal || this.shouldReturnTotal) {
```suggestion
		if(this.shouldReturnTotal) {
```

2023-09-06 21:55 UTC, gastonpereyra approved these changes

2023-10-03 14:38 UTC, merged