Jcn 318 fix bug with custom filters
janis-commerce/api-list pull request #7
Opened 2020-12-18 19:50 UTC by maguimarijuan

**Link al ticket**
https://fizzmod.atlassian.net/browse/JCN-317
**Link a la subtarea**
https://fizzmod.atlassian.net/browse/JCN-318
**Descripción del requerimiento**
Se requiere modificar el package API List para que al usar valueMapper custom pueda formatear un dato simple o un array de datos.

2020-12-18 20:07 UTC, gastonpereyra requested changes
Faltan Tests para chequear si funciona con los filtersMappers como el `searchMapper` o un `customMapper`

2020-12-22 16:41 UTC, gastonpereyra commented on lib/filter-mappers.js
> +	searchMapper: {
:bulb: 

Y si search es un caso particular de custom ? :smile_cat: 

```suggestion
	searchMapper: customTypeMapper('search'),
	customTypeMapper
```

2020-12-22 18:19 UTC, gastonpereyra approved these changes
Aprobado

2020-12-23 12:55 UTC, juanhapes requested changes

2020-12-23 12:55 UTC, juanhapes commented on lib/data-helpers/filter.js
> +	applyFilter(originalValue, valueMapper) {
Propongo `mapValue()` porque no estamos aplicando un filtro, estamos mapeando un valor (o _n_ valores)

2020-12-23 13:00 UTC, merged