Jcn 351 multiple sort direction to api list package
janis-commerce/api-list pull request #9
Opened 2022-02-08 00:00 UTC by MarianoFndz

### Link al ticket
- https://fizzmod.atlassian.net/browse/JCN-351
- https://fizzmod.atlassian.net/browse/JCN-352

### Descripción del requerimiento
Se requiere mejorar el package [npm: @janiscommerce/api-list](https://www.npmjs.com/package/@janiscommerce/api-list)  para poder implementar múltiples ordenamientos.
Ordenamiento
Se deberá poder ordenar por múltiples fields de la siguiente forma:
- Sin sortDirection:
  - Request: 
    - ?sortBy[0]=field1&sortBy[1]=field2
  - Resultado: 
    - sortBy: ['field1', 'field2'],
    - sortDirection: ['asc', 'asc'] // se toma el default del package
- Con sortDirection igual para cada field:
  - Request: 
    - ?sortBy[0]=field1&sortBy[1]=field2&sortDirection=asc
  - Resultado: 
    - sortBy: ['field1', 'field2'],
    - sortDirection: ['asc', 'asc']
- Con sortDirection definido para un field:
  - Request: 
    - ?sortBy[0]=field1&sortBy[1]=field2&sortDirection[1]=desc
  - Resultado: 
    - sortBy: ['field1', 'field2'],
    - sortDirection: ['asc', 'desc']
### Changelog
- Add multiple sort fields and sort directions

2022-02-08 13:06 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +const sortDirections = ['asc', 'desc', 'ASC', 'DESC', undefined];
no termino de entender porque `undefined` es un `sort direction` valido..

2022-02-08 13:26 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +		const response = {
no tiene mucho sentido esta variable..

2022-02-08 13:28 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +		if(typeof sortParameters === 'string') {
podrias guardar en una variable con un nombre que haga referencia a la intencion de la condicion que estas evaluando para no andar matcheando en diferentes lados por el tipo de dato

2022-02-08 13:48 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +		if(!sortParameters)
guarda que esta variable puede terminar almacenando un array vacio

2022-02-08 13:51 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +			const sortDirection = clientParamsWithDefaults[SORT_DIRECTION_PARAMETER];
necesitas iterar esto?

2022-02-08 13:58 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +		}, response);
resumidamente, la idea del reduce es aplicar una funcion a cada item de un array y retornar un unico valor, que seria tu acumulador y no esta variable que creaste mas arriba

2022-02-08 14:01 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +			accumOfParam.order[param] = sortDirection instanceof Array && sortDirection[index] ? sortDirection[index].toLowerCase() : DEFAULT_SORT_DIRECTION;
lo mismo que te dije mas arriba sobre las condiciones.. por otro lado, no te conviene por ahi 'sanitizar' los valores para no tirar el `lowercase` por diferentes partes de la funcion?

2022-02-08 14:14 UTC, fedeatanasoff commented on tests/api-list-data.js
> +		it('Should validate if sortBy property is passed as array', async () => {
capaz te convenga agrupar estos casos de prueba con arrays en un context aparte para no tener que especificar en cada descripcion que es un array..

2022-02-08 14:53 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +const sortDirections = ['asc', 'desc', 'ASC', 'DESC', undefined];
esto me hace mucho ruido.. ademas ahora `undefined` pasaria ser valido para el caso  que ya estaba andando.. tal vez deberias manejarlo en el struct para los casos donde pueda venir un array y no aca, ademas de que ya tenes un sort direction default

2022-02-08 14:56 UTC, fedeatanasoff requested changes
sumado a los comentarios que deje en el codigo, ni vi que se haya desarrollado e implementado lo de la cantidad maxima de fields a ordenar ni tampoco la documentacion

2022-02-08 15:35 UTC, MarianoFndz commented on lib/data-helpers/sort.js
> +			const sortDirection = clientParamsWithDefaults[SORT_DIRECTION_PARAMETER];
Si porque necesito iterar el param sortBy[....] y asignarles el sortDirection[....] correspondiente. (Con el mismo index)

2022-02-08 15:36 UTC, MarianoFndz commented on lib/data-helpers/sort.js
> +		}, response);
Queria reciclar, pero esta bien borro la variable, va a quedar mejor :+1:

2022-02-08 15:47 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +			const sortDirection = clientParamsWithDefaults[SORT_DIRECTION_PARAMETER];
pero la estas creando en cada iteracion y no depende de eso

2022-02-17 18:22 UTC, fedeatanasoff requested changes
deje algunos comentarios y consultas

2022-02-17 18:22 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +			[SORT_PARAMETER]: struct.optional(struct.dynamic(value => {
ya que aca tenes dos formas de aceptar esta prop y de paso ahorrarte lo de preguntar si le llego un array o un string , que te parece validar la estructura con `struct.union` ?

quedaria algo asi:

```
[SORT_PARAMETER]: struct.optional(struct.union([[struct.enum(this.sortableFields)], struct.enum(this.sortableFields)]))
```

el `union` en este caso te va a evaluar que lo que llegue ahi sea algo de los 2 tipos que le pasas y el resto de las validaciones las manejas desde el validate como hacemos siempre

2022-02-17 18:22 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +					if(this.isString(this.requestParameters[SORT_PARAMETER]))
no se si vas a seguir lo que te recomende mas arriba pero independientemente de eso si queres acceder a alguna prop desde dentro de un `struct.dynamic` deberias de hacerlo desde el `parent` que te devuelve la misma funcion `struct.dynamic( (value, parent) = > ... `

2022-02-17 18:22 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +		return sortParameters.reduce((accumOfParam, param, index) => {
este `accumOfParam` serian filters, no? en caso de que no sean igual pongamosle un nombre mas representativo

2022-02-17 18:22 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +			accumOfParam.order[param] = sortDirection instanceof Array && sortDirection[index] ? sanitizedSortDirection[index] : DEFAULT_SORT_DIRECTION;
si `sortDirection` no es un array siempre va a tomar el valor default?

2022-02-17 18:22 UTC, fedeatanasoff commented on README.md
> +💡 Also, we can pass **sortBy** as `array`
si bien entiendo que quisiste respetar el formato de como se declaro algo mas abajo, este al tener mas puntos para explicar mas alguna anotación que tiene se vuelve medio confuso identificar donde empieza o termina lo relacionado a cada uno .. creo que lo que rompe un poco el orden son esas lineas donde empiezan con el emoji en lugar de la declaracion del filtro como el resto
![image](https://user-images.githubusercontent.com/15443855/154545467-73f4cf2e-7390-4390-8b9f-54ed18425e23.png)

2022-02-21 03:45 UTC, MarianoFndz commented on lib/data-helpers/sort.js
> +		return sortParameters.reduce((accumOfParam, param, index) => {
Lo cambio a accumOfFields
Ya que no son filters en realidad
`
page: 2,
				limit: 20,
				order: {
					foo: 'desc'
				},
				filters: {
					id: '10',
					id2: 100,
					someParent: 1,
					'rootProperty.myProp': true
				}
`

2022-02-21 05:08 UTC, fedeatanasoff commented on lib/data-helpers/sort.js
> +		return sortParameters.reduce((accumOfParam, param, index) => {
ok.. mandale `params` entonces.. `accumOf` no te suma nada..

2022-02-24 21:34 UTC, manuelvilche requested changes

2022-02-24 21:34 UTC, manuelvilche commented on README.md
> +const {
```suggestion
const { ApiListData } = require('@janiscommerce/api-list');
```
Aca si lo dejamos todo en una misma linea, ocupamos menos espacio! 🤓

2022-02-24 21:34 UTC, manuelvilche commented on README.md
> +* `/api/entity?sortBy=foo&&sortDirection=desc` with a single value.
Fijate que en todos los casos tenes un `&&` en ves de un `&`

2022-02-24 21:34 UTC, manuelvilche commented on lib/data-helpers/sort.js
> +			throw new Error('The field sortDirection must be string when sortBy is string');
@MarianoFndz Esto es bastante polémico! Acá lo que podríamos hacer, es que si el `sortBy` es un string y el `sortDirection` un array, buscar el calor del primer `index`, o usar el default! pero nose si tiene mucho sentido devolver un error, cuando podemos encontrar un fallback, como la ves?!

2022-02-26 21:06 UTC, merged